name: helm Action

on:
  workflow_dispatch:
  push:
   branches:
     - new

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
         
      - name: Retrieve kubeconfig secret
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig.yaml
        
          
      - name: Verify AWS CLI installation
        run: aws --version

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_DEFAULT_REGION
 
 
      - name: Get list of pods
        env:
          KUBECONFIG: ./kubeconfig.yaml
        run: |
          kubectl get pods
          
      - name: helm command run
        env:
          KUBECONFIG: ./kubeconfig.yaml
        uses: WyriHaximus/github-action-helm3@v3
        with:
            exec: helm ls
