on:
  push:
    branches: [ main ]

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: vijaybishtrkt@gmail.com
        password: ${{ secrets.APPPASSWD }}
        to: vijaybisht0103@gmail.com,shivani.singh@opstree.com
        from: vijaybishtrkt@gmail.com
        subject: 'Test email with HTML body'
        html_body: |
            <p>
              <h2 style="color: red;">Workflow Status: ${{ job.status }}</h2>
              <br>
              Workflow URL: <a href="${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}">${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}</a>
              <br>    
              Workflow Trigger: ${{ github.event_name }}
            </p>

        content_type: html
        convert_markdown: true

 

