on:
  push:
    branches: [ main ]

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: shivani.singh@opstree.com
        password: rcbnxnnaftzexufd
        to: shivani.singh@opstree.com
        from: shivani.singh@opstree.com
        subject: 'Test email with HTML body'
        html_body: |
          <h2 style="color: pink;">Workflow Status: ${{ job.status }}</h2>
          <p>
            Workflow URL: <a href="${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}">${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}</a>
          <br>
            Workflow Trigger: ${{ github.event_name }}
          <br>
            Application health check URL: <a href="http://qa.bigparser.com/api/v2/test_devops">Qa.bigparser.com/api/v2/test_devops</a>
          </p>


        #content_type: html
        #convert_markdown: true

 

