name: Kubectl Action

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Check kubectl version
        run: kubectl version --client
        
      - name: Install Python and AWS CLI
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install AWS CLI
        run: sudo apt-get update && sudo apt-get install -y awscli
        
      - name: Verify AWS CLI installation
        run: aws --version
 
      - uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.0' # default is latest stable
        id: install
 
      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_DEFAULT_REGION
      
      - name: Deploy to cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        with:
          args: kubectl get po

