name: Checkout Two Repositories and Verify

on:
  push:
    branches:
    

jobs:
  checkout-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo 1
        uses: actions/checkout@v2
        with:
          ref: main
          
      - name: Create mytool Folder
        run: mkdir mytool
        
      - name: Checkout Repo 2
        uses: actions/checkout@v2
        with:
          repository: bishtraja/private
          ref: main
          path: mytool
          token: ${{ secrets.TOKEN }}
          
      - name: Verify Repo 2 is Cloned Inside mytool Folder
        run: |
          ls mytool
          echo "Contents of mytool folder:"
          cat mytool/*
