name: Checkout Two Repositories and Verify

on:
  push:
    branches:
      - main

jobs:
  checkout-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo 1
        uses: actions/checkout@v2
        with:
          repository: username/repo1
          ref: main
      - name: Create mytool Folder
        run: mkdir mytool
      - name: Checkout Repo 2
        uses: actions/checkout@v2
        with:
          repository: username/repo2
          ref: main
          path: mytool
      - name: Verify Repo 2 is Cloned Inside mytool Folder
        run: |
          ls mytool
          echo "Contents of mytool folder:"
          cat mytool/*
