name: Send email to me

on:
  workflow_dispatch:
jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Send email
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: vijaybishtrkt
        password: ${{ secrets.APPPASSWD }}
        from: vijaybishtrkt@gmail.com
        subject: My email subject
        body: |
          $(envsubst < email-template.html)
        to: vijaybisht0103@gmail.com
        content_type: text/html
        convert_markdown: true
        
    - name: Substitute environment variables
      run: |
        sudo apt-get -y update
        sudo apt-get -y install gettext
        envsubst < email-template.html > email-template-envsubst.html
