name: Send Email Notification

on: 
 workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Render Email Template
      uses: gohugoio/hugo-action@v2
      with:
        hugo_args: --templateMetrics --templateMetricsHints
        buildDrafts: false
        minify: true
        src: 'email-template.html'
        destination: 'email-template'

    - name: Send Email
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: vijaybishtrkt
        password: ${{secrets.APPPASSWD}}
        subject: GitHub Actions Notification
        body: ${{ steps.render-email-template.outputs.content }}
        to: vijaybisht0103@gmail.com
        from: vijaybishtrkt@gmail.com

