name: Send email to me

on:
  workflow_dispatch:
jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read email template
      id: email-template
      run: echo "::set-output name=content::$(cat email-template.html)"

    - name: Send email
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: vijaybishtrkt
        password: ${{ secrets.APPPASSWD }}
        from: vijaybishtrkt@gmail.com
        subject: My email subject
        body: ${{ steps.email-template.outputs.content }}
        to: vijaybisht0103@gmail.com
        content_type: text/html

