name: Send Email from python

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install Jinja2
        run: pip install jinja2

      - name: Set Job Status
        run: |
          echo "export JOB_STATUS=Success" >> $GITHUB_ENV

      - name: Render HTML Email Template
        run: |
          echo "export GITHUB_REPOSITORY=$GITHUB_REPOSITORY" >> $GITHUB_ENV
          echo "export GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          echo "export GITHUB_REF=$GITHUB_REF" >> $GITHUB_ENV
          echo "export GITHUB_HEAD_REF=$GITHUB_HEAD_REF" >> $GITHUB_ENV
          echo "export GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME" >> $GITHUB_ENV
          echo "export GITHUB_SHA=$GITHUB_SHA" >> $GITHUB_ENV
          echo "export GITHUB_ACTOR=$GITHUB_ACTOR" >> $GITHUB_ENV
          echo "export GITHUB_WORKFLOW=$GITHUB_WORKFLOW" >> $GITHUB_ENV
          python render_template.py

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: vijaybishtrkt
          password: ${{ secrets.APPPASSWD }}
          subject: Workflow Status
          body: |
            Workflow URL: ${GITHUB_SERVER_URL}/${{ github.event.repository }}/actions/runs/${{ github.run_id }}
            Workflow Trigger: ${{ github.event_name }}
            Application health check URL: http://Qa.bigparser.com/api/v2/test_devops
            {{ github.workflow }} - Successful
            GitHub Repository: ${{ env.GITHUB_REPOSITORY }}
            Github Actions Build Number: ${{ github.run_number }}
            GitHub Branch Name: ${{ github.ref }}
            Commit Message: ${{ github.event.head_commit.message }}
            Status: Success
          from: vijaybishtrkt@gmail.com
          to: vijaybishtrkt@gmail.com

