name: Send Email from python

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Jinja2
        run: pip install jinja2

      - name: Render HTML Email Template
        run: |
          python render_template.py

      - name: Send Email
        uses: dawidd6/action-send-mail@v3.3.1
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: vijaybishtrkt
          password: ${{ secrets.APPPASSWD }}
          subject: Workflow Status:${{ job.status }}
          body: |
            Workflow URL: ${GITHUB_SERVER_URL}/${{ github.event.repository }}/actions/runs/${{ github.run_id }}
            Workflow Trigger: ${{ github.event_name }}
            Application health check URL: http://Qa.bigparser.com/api/v2/test_devops
            ${GITHUB_WORKFLOW} - Successful
            GitHub Repository: ${{github.repository}}
            Github Actions Build Number: ${{ github.run_number }}
            GitHub Branch Name: ${{ github.ref }}
            Commit Message: ${{ github.event.head_commit.message }}
          from: vijaybishtrkt@gmail.com
          to: vijaybishtrkt@gmail.com
          
          





